In [1]:
import pandas as pd

import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
data_df = pd.read_csv('../data/raw_refahdb.zip')
data_df

,ID,ParentID,BirthDate,GenderId,postalcode,Provincename,countyname,isurban,AmCrdtr_95,Amdbtr_95,...,Cars_Count,CarsPrice_Sum,Trips_Count_AirNotPilgrimage,Trips_Count_NotAirNotPilgrimage,Trips_Count_AirPilgrimage,Trips_Count_NotAirPilgrimage,HasMojavezSenfi,Senf,HasBimeSalamat,BimeSalmat_Type
0,385996899,391863876,1978-03-22,2,6451967.0,خوزستان,شوشتر,True,207500000,307500000,...,0,0,0,0,0,0,0,NaN,0,NaN
1,2633686968,2633686968,1995-02-05,1,9577153.0,خراسان رضوي,تربت جام,True,137500000,110000000,...,1,795867494,0,0,0,0,0,NaN,1,روستاييان
2,312125928,1981002597,1970-05-13,2,3898155.0,مرکزي,خمين,False,0,0,...,0,0,0,0,0,0,0,NaN,1,روستاييان
3,70847160,70847160,1969-03-21,1,8318747.0,اصفهان,شاهين شهر و ميمه,True,135000000,167500000,...,1,913334400,0,0,0,0,0,NaN,0,NaN
4,663191175,9230116821,2004-06-19,2,451879.0,زنجان,زنجان,True,2500000,0,...,0,0,0,0,0,0,0,NaN,1,کارکنان دولت
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490986,4822361022,4822361022,1973-04-21,1,4384186.0,گيلان,رضوانشهر,True,7500000,7500000,...,1,855771499,0,0,0,0,0,NaN,1,روستاييان
1490987,2816587107,2816587107,1942-07-01,1,371474.0,قم,قم,True,227500000,375000000,...,0,0,0,0,1,0,0,NaN,1,ايرانيان
1490988,6680054253,6680054253,1945-09-11,1,5438134.0,آذربايجان شرقي,مرند,False,187500000,187500000,...,1,523117116,0,0,0,0,0,NaN,1,روستاييان
1490989,4142421696,4142421696,1977-09-21,1,7169644.0,فارس,شيراز,True,327500000,375000000,...,2,1661819838,0,0,0,0,0,NaN,1,سايراقشار-نظام ارجاع 1
1490990,1424664495,4711403091,2005-05-12,1,8615835.0,اصفهان,شهرضا,True,0,0,...,0,0,0,0,0,0,0,NaN,1,بيمه سلامت همگاني